### PR TITLE
Switch to https://schema.org

### PR DESCRIPTION
**Pull request by nickevansuk**
This switches the enumeration values and @context to "https" to ensure that this library meets stricter standards requirements where "https" is already being enforced today, while retaining backwards compatibility in deserialization.

"Over time we will migrate the schema.org site itself towards using https:  as the default version of the site and our preferred form in examples." - https://schema.org/docs/faq.html#19

Note that [this commit](https://github.com/RehanSaeed/Schema.NET/pull/89/commits/e07688964a486db726389d5e24a9a01879c48c22) contains the changes excluding the regenerated classes, to simplify review.

### CODE REVIEW

**Comment by RehanSaeed** [comment]
Thank you @nickevansuk!!!

**Comment by nickevansuk** [comment]
Hey @RehanSaeed, so you have an ETA of when this may be released?

**Comment by RehanSaeed** [comment]
Just released. CI server should publish soon:

https://github.com/RehanSaeed/Schema.NET/releases/tag/Schema.NET.6.0.0

**Comment by nickevansuk** [comment]
Fantastic, thanks!!

**Pull request merged**
