### PR TITLE
Add release-drafter

### PR DESCRIPTION
**Pull request by RehanSaeed**
Automatically drafts releases. Living the dream!

https://github.com/marketplace/actions/release-drafter

- PR's with `enhancement` or `dependencies` labels are marked as new features.
- PR's with `bug` labels are marked as bug fixes.
- PR's with new `maintenance` labels are marked as maintenance.
- PR's with `major`, `minor` or `patch` labels determine the version number generated in the release. The default is patch if no label is specified. Since we use MinVer, it takes the release version and then automagically uses that to version and deploy the NuGet package.

In theory, all I need to do now, is hit the big green publish button.

### CODE REVIEW

**Comment by Turnerj** [comment]
If I understand this right, it sounds really awesome! Basically every PR merged "builds" a draft release on GitHub and when you're ready, you just publish that release yeah?

**Comment by RehanSaeed** [comment]
That's the idea. This is the first time I've tried it.

**Comment by Turnerj** [comment]
Cool - I'll go over it more thoroughly tomorrow but at a glance, it looks good to me. 🙂

**Comment by Turnerj** [comment]
Just FYI, we don't have the Major, Minor or Patch labels setup yet.

**Comment by RehanSaeed** [comment]
Same. This is the test bed repo.

Added the labels.

**Pull request merged**
